<a href="https://colab.research.google.com/github/yeseul515/sessac_test2/blob/main/231017(Tue)_%EB%B9%85%EB%B6%84%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy
- numpy의 기반 데이터 타입은 다차원 배열(ndarray)
- 다차원 배열: 같은 자료형의 데이터를 담을 수 있는 하나의 그릇



## (1) numpy 배열 생성

In [ ]:
# 212-01
import numpy as np

In [ ]:
# 212-02
a1 = np.array([1, 2, 3])
print(a1)
print('array1 type: ', type(a1))
print('array1 shape: ', a1.shape) #1차원 배열에 3개의 데이터 구조

a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)
print('array2 type: ', type(a2))
print('array2 shape: ', a2.shape) #2차원 배열에 2개의 행과 3개의 컬럼 데이터 구조

a3 = np.array([[1, 2, 3]])
print(a3)
print('array3 type: ', type(a3))
print('array3 shape: ', a3.shape) #2차원 배열에 1개의 행과 3개의 컬럼 데이터 구조

[1 2 3]
array1 type:  <class 'numpy.ndarray'>
array1 shape:  (3,)
[[1 2 3]
 [4 5 6]]
array2 type:  <class 'numpy.ndarray'>
array2 shape:  (2, 3)
[[1 2 3]]
array3 type:  <class 'numpy.ndarray'>
array3 shape:  (1, 3)


In [ ]:
# 212-03 각 배열의 차원 확인

print('array1 dim: ', a1.ndim)
print('array2 dim: ', a2.ndim)
print('array3 dim: ', a3.ndim)

array1 dim:  1
array2 dim:  2
array3 dim:  2


In [ ]:
# 212-04

a = np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
# 212-05
a = np.arange(1, 20, 3)
print(a)

[ 1  4  7 10 13 16 19]


## (2) numpy 배열 초기화
- 0 또는 1로 초기화해야 할 필요가 있는 경우 → zeros, ones 함수 이용
- zeros 함수는 매개변수로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 배열을 생성(ones 함수는 1로 채운 배열 생성)

In [ ]:
# 213-01
import numpy as np

zero_a = np.zeros((2, 5))
one_a = np.ones((3, 4))

print(zero_a)
print(one_a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# 213-02 이미 생성된 배열 구조와 동일한 구조를 유지한 상태에서 0으로 채워진 배열로 초기화하여 생성하는 방법(one_a의 배열 구조를 유지하면서 0으로 채우는 방법)

zero_b = np.zeros_like(one_a)
print(zero_b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# 213-03

one_b = np.ones_like(zero_a)
print(one_b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# 213-04 모든 값이 특정 상수인 배열을 생성하거나 임의의 값으로 채워진 배열 생성

full_a = np.full((4, 3), 9)
random_a = np.random.random((3, 4))

print(full_a)
print(random_a)

[[9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]]
[[7.98187866e-01 6.44436133e-01 1.85583885e-01 7.34888602e-01]
 [7.58966821e-04 6.14709284e-01 6.30077401e-01 2.70878972e-01]
 [9.39723495e-01 3.34127109e-01 3.76436141e-01 8.49507966e-01]]


In [ ]:
# 213-05 주대각선의 원소가 모두 1이고, 나머지는 모두 0인 대각행렬 형태의 배열 생성

eye_a = np.eye(4)
print(eye_a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## (4) numpy 배열 크기 변형
- reshape( ) : 배열의 차원과 크기를 변경하는 함수. 변환하고자 하는 크기를 함수 인자로 입력하면 됨
- reshape 함수의 옵션으로 'order="F"'를 선언하면 값을 열부터 채움(옵션을 입력하지 않으면 행부터 채움)
- reshape 함수는 지정된 크기로 변경이 불가능하면 오류 발생
ex) (10, ) 배열 데이터를 (4, 3) 배열 데이터로 바꿀 수 없음

In [ ]:
# 214-01

array1 = np.arange(12)
print("array1: \n", array1)

array2 = array1.reshape(3, 4)
print("array2: \n", array2)

array3 = array1.reshape(3, 4, order='F')
print("array3: \n", array3)

array1: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
array2: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
array3: 
 [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [ ]:
# 214-02

array1 = np.arange(10)
array2 = array1.reshape(-1, 5) #array1과 호환될 수 있는 2차원 배열로 변환하되, 고정된 5개의 컬럼에 맞는 행을 자동으로 새롭게 생성해 변환

print(array2)
print("array2 dim: ", array2.ndim)
print("array2 shape: ", array2.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
array2 dim:  2
array2 shape:  (2, 5)


In [ ]:
# 214-03

array1 = np.arange(12)
array2 = array1.reshape(2, 3, 2, order='F')

print(array2)
print("array2 dim: ", array2.ndim)
print("array2 shape: ", array2.shape)

[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]
array2 dim:  3
array2 shape:  (2, 3, 2)


In [ ]:
# 213-04 다차원 배열을 1차원 배열로 만들기

array3 = array2.flatten()
print(array3)

[ 0  6  2  8  4 10  1  7  3  9  5 11]


## (5) numpy 배열 데이터 추출하기
- 인덱싱(indexing)
- 슬라이싱(slicing) : 슬라이싱으로 추출된 데이터 세트는 배열 타입

In [ ]:
# 215-01 1차원 배열에서 한 개의 데이터 추출하기

array1 = np.arange(1, 10)
print("array1: ", array1)

value1 = array1[2]
value2 = array1[-2]

print(value1)
print(value2)

array1:  [1 2 3 4 5 6 7 8 9]
3
8


In [ ]:
# 215-02 다차원 배열에서 단일 값 추출하기

array1 = np.arange(1, 10)
array2 = array1.reshape(3, 3)
print("array2 : \n", array2)

value1 = array2[0, 0]
value2 = array2[-1, -1]
value3 = array2[-1, -2]

print(value1)
print(value2)
print(value3)

array2 : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
1
9
8


In [ ]:
# 215-03

array1 = np.arange(1, 10)
array2 = array1[0:3]
array3 = array1[:3]
array4 = array1[3:]

print(array1)
print(type(array2))
print(array2)
print(array3)
print(array4)


[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[1 2 3]
[1 2 3]
[4 5 6 7 8 9]


In [ ]:
# 215-04

array1 = np.arange(1, 10)
array2 = array1.reshape(3, 3)
print("array2 : \n", array2)

print("array2[0:2, 0:2]: \n", array2[0:2, 0:2])
print("array2[1:3, 0:3]: \n", array2[1:3, 0:3])
print("array2[:2, 1:]: \n", array2[:2, 1:])
print("array2[:2, 0]: ", array2[:2, 0])

array2 : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2[0:2, 0:2]: 
 [[1 2]
 [4 5]]
array2[1:3, 0:3]: 
 [[4 5 6]
 [7 8 9]]
array2[:2, 1:]: 
 [[2 3]
 [5 6]]
array2[:2, 0]:  [1 4]


## (6) numpy 선형대수 기본 연산
- 행렬 내적(행렬 곱) : 두 행렬 A와 B의 내적은 np.dot함수를 이용
- 전치 행렬 : 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬(np.transpose)

In [ ]:
# 216-01

array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])
array2 = np.array([[7, 8],
                   [9, 10],
                   [11, 12]])

dot_array = np.dot(array1, array2)
print(dot_array)

[[ 58  64]
 [139 154]]


In [ ]:
# 216-02

array1 = np.array([[1, 2, 3],
                  [4, 5, 6]])
print("array1: \n", array1)
transpose_array = np.transpose(array1)

print(transpose_array)

array1: 
 [[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


## (7) numpy 기술통계

In [ ]:
# 217-01 배열 데이터 개수 계산
x = np.array([18, 5, 10, 23, 19, -8, 10, 0, 0, 5, 2, 15, 8,
              2, 5, 4, 15, -1, 4, -7, -24, 7, 9, -6, 23, -13])

len(x)

26

In [ ]:
# 217-02 평균, 분산, 표준편차 계산
print(np.mean(x))
print(np.var(x))
print(np.std(x))

4.8076923076923075
115.23224852071006
10.734628476137871


In [ ]:
# 217-03 최대값, 최소값, 중앙값 계산
print(np.max(x))
print(np.min(x))
print(np.median(x))

23
-24
5.0


In [ ]:
# 217-04 사분위수 계산
print(np.percentile(x, 25)) #1사분위수
print(np.percentile(x, 50)) #2사분위수
print(np.percentile(x, 75)) #3사분위수

0.0
5.0
10.0
